steps:
  - name: "gcr.io/cloud-builders/docker"
    args: 
      - ['build', '-t', 'us-central1-docker.pkg.dev/rapid-shine-435918-e2/minaz-100966820/my-image:$COMMIT_SHA', './']

  - name: "gcr.io/cloud-builders/docker"
    args:
      - ['push', 'us-central1-docker.pkg.dev/rapid-shine-435918-e2/minaz-100966820/my-image:$COMMIT_SHA']

images:
  - 'us-central1-docker.pkg.dev/rapid-shine-435918-e2/minaz-100966820/my-image:$COMMIT_SHA'
  
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
